LuxoftSDL/sdl_atf_test_scripts

test_scripts/Capabilities/PersistingHMICapabilities/common.lua

Update receiving of HMI capabilities cache file using module SDL

[SDL-0249] Update receiving of HMI capabilities cache file using module SDL

---

test_scripts/WebEngine/WebEngineProjection/002_Check_WS_connection_for_WebEngine_projection_app_in_NONE.lua
test_scripts/WebEngine/WebEngineProjection/003_Check_WSS_connection_for_WebEngine_projection_app_in_NONE.lua
test_scripts/WebEngine/WebEngineProjection/004_Check_that_SDL_forwards_OnSystemCapabilityUpdated_notification_to_WebEngine_projection_app.lua
test_scripts/WebEngine/WebEngineProjection/005_OnExitApplication_RESOURCE_CONSTRAINT_unregister.lua
test_scripts/WebEngine/WebEngineProjection/006_Registration_reject_WEB_VIEW_when_PT_is_empty.lua
test_scripts/WebEngine/WebEngineProjection/007_Registration_reject_WEB_VIEW_is_absent_in_PT.lua
test_scripts/WebEngine/commonWebEngine.lua

Added WEB_VIEW to preloaded PT for success registration and new scripts for check reject registration.

Updated scripts for success WEB_VIEW registration

---

test_scripts/Defects/4_5/1206_REQUEST_PTU_Trigger_PTU_failed_previous_IGN_ON.lua
test_scripts/Defects/4_5/1873_Parameters_empty_in_policy_table.lua
test_scripts/Defects/5_0/2446_SDL_doesn_t_resume_HMILevel_when_DEACTIVATE_HMI_with_isActive_is_true_then_false.lua

http://172.26.147.12/view/0249_persisting_hmi_capabilities/job/0249_persisting_hmi_capabilities_ATF_Defects_5.x-4.x_P/28/#showFailuresLink
Do not persist HMI Capabilities received from headunit

[SDL-0249] - Update regression scripts to do not persist HMI Capabilities

---

test_scripts/WebEngine/WebEngineProjection/001_Registration.lua
test_scripts/WebEngine/WebEngineProjection/002_Check_WS_connection_for_WebEngine_projection_app_in_NONE.lua
test_scripts/WebEngine/WebEngineProjection/003_Check_WSS_connection_for_WebEngine_projection_app_in_NONE.lua
test_scripts/WebEngine/WebEngineProjection/004_Check_that_SDL_forwards_OnSystemCapabilityUpdated_notification_to_WebEngine_projection_app.lua
test_scripts/WebEngine/WebEngineProjection/005_OnExitApplication_RESOURCE_CONSTRAINT_unregister.lua
test_scripts/WebEngine/WebEngineProjection/008_Registration_appHMIType_is_array.lua
test_scripts/WebEngine/commonWebEngine.lua
test_sets/webengine_projection_mode.txt

ATF Test Scripts to check ??
Added script that checks whether it is possible to register App with array of HMI types [WEB_VIEW, Media].
develop

[SDL-0273] Add 008_Registration_appHMIType_is_array script

---

test_scripts/WebEngine/WebEngineProjection/001_Registration.lua
test_scripts/WebEngine/WebEngineProjection/002_Check_WS_connection_for_WebEngine_projection_app_in_NONE.lua
test_scripts/WebEngine/WebEngineProjection/003_Check_WSS_connection_for_WebEngine_projection_app_in_NONE.lua
test_scripts/WebEngine/WebEngineProjection/004_Check_that_SDL_forwards_OnSystemCapabilityUpdated_notification_to_WebEngine_projection_app.lua
test_scripts/WebEngine/WebEngineProjection/005_OnExitApplication_RESOURCE_CONSTRAINT_unregister.lua
test_scripts/WebEngine/WebEngineProjection/006_Registration_reject_WEB_VIEW_when_PT_is_empty.lua
test_scripts/WebEngine/WebEngineProjection/007_Registration_reject_WEB_VIEW_is_absent_in_PT.lua
test_scripts/WebEngine/WebEngineProjection/008_Registration_appHMIType_is_array.lua
test_scripts/WebEngine/WebEngineProjection/009_OnSCU_after_Show_main.lua
test_scripts/WebEngine/WebEngineProjection/010_OnSCU_after_Show_widget.lua
test_scripts/WebEngine/commonWebEngine.lua
test_sets/webengine_projection_mode.txt

ATF Test Scripts to check Forwarding of OnSystemCapabilityUpdated notification to WEB_VIEW app
- Window Capabilities receiving via OnSystemCapabilityUpdated notification for when application change template from WEB_VIEW
- Window Capabilities receiving via OnSystemCapabilityUpdated notification when WEB_WIEV application process Show RPC for widget
develop

[SDL-0273] Forwarding of OnSystemCapabilityUpdated notification to WEB_VIEW app

---

test_scripts/WebEngine/WebEngineProjection/006_Registration_disallowed_WEB_VIEW_when_PT_is_empty.lua

https://adc.luxoft.com/jira/browse/FORDTCN-6808
Fix of 006 script for registration failure cases.
develop

[SDL-0273] Fix of 006 script for registration failure cases

---

test_scripts/WebEngine/WebEngineProjection/019_Create_widget.lua
test_scripts/WebEngine/WebEngineProjection/020_Create_widget_with_DuplicateId.lua
test_scripts/WebEngine/WebEngineProjection/021_Show_RPC_to_Main_Window_widget_without_DuplicateID.lua
test_scripts/WebEngine/WebEngineProjection/022_Show_RPC_to_Main_Window_widget_with_DuplicateID.lua
test_sets/webengine_projection_mode.txt

https://adc.luxoft.com/jira/browse/FORDTCN-6816
ATF Test Scripts to check the creation of widget when application has active WEB_VIEW template
- Processing the creation of widget which do not duplicate main window when application has active WEB_VIEW template
- Processing the creation of widget which duplicate main window
- Processing of RPCs for widgets which do not duplicate main window
- Processing of RPCs for widget which duplicate main window
[develop]

[SDL-0273] Widgets processing for WEB_VIEW template

---

test_scripts/UpdateVideoStreamingCapabilities/001_1_GetCapabilities_with_addVSC.lua
test_scripts/UpdateVideoStreamingCapabilities/001_2_GetCapabilities_without_AddVSC.lua
test_scripts/UpdateVideoStreamingCapabilities/001_3_GetCapabilities_in_range_minsize_maxsize_array.lua
test_scripts/UpdateVideoStreamingCapabilities/001_4_GetCapabilities_out_of_range_minsize_maxsize_array.lua
test_scripts/UpdateVideoStreamingCapabilities/001_5_GetCapabilities_invalid_AddVSC.lua
test_scripts/UpdateVideoStreamingCapabilities/001_6_GetCapabilities_AddVSC_missing_all_param.lua
test_scripts/UpdateVideoStreamingCapabilities/001_7_GetCapabilities_with_addVSC_only.lua
test_scripts/UpdateVideoStreamingCapabilities/001_8_GetCapabilities_with_addVSC_nested.lua
test_scripts/UpdateVideoStreamingCapabilities/001_9_GetCapabilities_with_addVSC_deep_nested.lua

ATF Test Scripts to check #[FORDTCN-6904](https://adc.luxoft.com/jira/browse/FORDTCN-6904)
Added descriptions in UI.GetCapabilities tests
develop

[SDL-0296] Descriptions for UI.GetCapabilities tests

---

test_scripts/UpdateVideoStreamingCapabilities/001_5_GetCapabilities_invalid_AddVSC.lua
test_scripts/UpdateVideoStreamingCapabilities/002_6_1_OnSystemCapabilityUpdated_invalid.lua

Fix in the scope of https://adc.luxoft.com/jira/browse/FORDTCN-6913
Unknown enums will be erased according to the  https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0298-Processing-of-unknown-enum-values-by-SDL-Core.md
develop

[SDL-0296] Replace unknown enums values with the invalid values 

---

test_scripts/Resumption/InteriorVehicleData/OnHashChange/001_OnHashChange_by_module_subscription_without_moduleId.lua
test_scripts/Resumption/InteriorVehicleData/OnHashChange/002_OnHashChange_by_module_subscription_with_moduleId.lua
test_scripts/Resumption/InteriorVehicleData/OnHashChange/003_OnHashChange_by_module_unsubscription_without_moduleId.lua
test_scripts/Resumption/InteriorVehicleData/OnHashChange/004_OnHashChange_by_module_unsubscription_with_moduleId.lua
test_scripts/Resumption/InteriorVehicleData/OnHashChange/005_OnHashChange_absence_with_subscribe_false_without_active_subscription_without_moduleId.lua
test_scripts/Resumption/InteriorVehicleData/OnHashChange/006_OnHashChange_absence_with_subscribe_false_without_active_subscription_with_moduleId.lua
test_scripts/Resumption/InteriorVehicleData/OnHashChange/007_OnHashChange_absence_with_subscribe_nil_without_active_subscription_without_moduleId.lua
test_scripts/Resumption/InteriorVehicleData/OnHashChange/008_OnHashChange_absence_with_subscribe_nil_without_active_subscription_with_moduleId.lua
test_scripts/Resumption/InteriorVehicleData/commonResumptionsInteriorVD.lua

ATF Test Scripts to check #(FORDTCN-7217)[https://adc.luxoft.com/jira/browse/FORDTCN-7217]
This PR is **[ready / not ready]** for review.
Tests for OnHashChange notification during processing of subsription to interior vehicle data
develop

[SDL-0188] Tests for OnHashChange

---

test_scripts/Resumption/InteriorVehicleData/023_InteriorVD_double_subscription_without_moduleId.lua
test_scripts/Resumption/InteriorVehicleData/024_InteriorVD_double_subscription_with_moduleId.lua
test_scripts/Resumption/InteriorVehicleData/025_InteriorVD_resumption_double_subscription_without_moduleId_unexpected_disconnect.lua
test_scripts/Resumption/InteriorVehicleData/026_InteriorVD_resumption_double_subscription_with_moduleId_unexpected_disconnect.lua

In the scope of https://adc.luxoft.com/jira/browse/FORDTCN-7215
Fix result code and steps description 
develop

[SDL-0188] fixup! Scripts for double subscriptions

---

test_scripts/Resumption/Handling_errors_from_HMI/001_successful_resumption_SUCCESS_resultCode.lua
test_scripts/Resumption/Handling_errors_from_HMI/005_resume_all_data_with_one_error_rpc_unexpected_disconnect.lua
test_scripts/Resumption/Handling_errors_from_HMI/006_resume_all_data_with_one_error_rpc_ign_off.lua
test_scripts/Resumption/Handling_errors_from_HMI/007_resume_all_data_with_one_rpc_2apps_unexpected_disconnect.lua
test_scripts/Resumption/Handling_errors_from_HMI/008_resume_all_data_with_one_rpc_2apps_ign_off.lua
test_scripts/Resumption/Handling_errors_from_HMI/017_resume_all_data_without_response_to_one_rpc_unexpected_disconnect.lua
test_scripts/Resumption/Handling_errors_from_HMI/018_resume_all_data_without_response_to_one_rpc_ign_off.lua
test_scripts/Resumption/Handling_errors_from_HMI/019_resume_all_data_without_response_to_one_rpc_2apps_unexpected_disconnect.lua
test_scripts/Resumption/Handling_errors_from_HMI/020_resume_all_data_without_response_to_one_rpc_2apps_ign_off.lua
test_scripts/Resumption/Handling_errors_from_HMI/032_Same_RPC_VD_RAI2_before_request_to_HMI.lua
test_scripts/Resumption/Handling_errors_from_HMI/034_Same_RPC_VD_RAI2_after_erroneous_response_from_HMI.lua
test_scripts/Resumption/Handling_errors_from_HMI/035_Same_RPC_WP_RAI2_before_request_to_HMI.lua
test_scripts/Resumption/Handling_errors_from_HMI/036_Same_RPC_WP_RAI2_before_erroneous_response_from_HMI.lua
test_scripts/Resumption/Handling_errors_from_HMI/037_Same_RPC_WP_RAI2_after_erroneous_response_from_HMI.lua
test_scripts/Resumption/Handling_errors_from_HMI/commonResumptionErrorHandling.lua

updates in descriptions and fixed some small format issues
develop

[SDL-0190] Small fixes

---

test_scripts/RC/AUDIO_LIGHT_HMI_SETTINGS/GetInteriorVehicleData/015_Transfering_of_isSubscribed_parameter_in_case_request_from_Mob_app_with_subscribe_parameter_but_response_from_HMI_without_isSubscribed.lua
test_scripts/RC/CLIMATE_RADIO/GetInteriorVehicleData/012_Transfering_of_isSubscribed_parameter_in_case_request_from_Mob_app_with_subscribe_parameter_but_response_from_HMI_without_isSubscribed.lua
test_scripts/RC/SEAT/GetInteriorVehicleData/010_Transfering_of_isSubscribed_parameter_in_case_request_from_Mob_app_with_subscribe_parameter_but_response_from_HMI_without_isSubscribed.lua
test_scripts/RC/SEAT/GetInteriorVehicleData/012_Absence_of_subscribe_parameter_in_request_for_HMI_in_case_of_2nd_Subscription_UnSubscription.lua

update regression test scripts to warning on double subscriptions
develop

[SDL-0188] fixup! update regression test scripts to warning on double subscriptions

---

test_scripts/Resumption/InteriorVehicleData/001_InteriorVD_resumption_one_moduleType_without_moduleId_unexpected_disconnect.lua
test_scripts/Resumption/InteriorVehicleData/002_InteriorVD_resumption_one_moduleType_with_moduleId_unexpected_disconnect.lua
test_scripts/Resumption/InteriorVehicleData/003_InteriorVD_resumption_same_moduletype_with_different_moduleIds_unexpected_disconnect.lua
test_scripts/Resumption/InteriorVehicleData/004_InteriorVD_resumption_all_modules_without_moduleId_unexpected_disconnect.lua
test_scripts/Resumption/InteriorVehicleData/005_InteriorVD_resumption_all_modules_with_moduleId_unexpected_disconnect.lua
test_scripts/Resumption/InteriorVehicleData/006_InteriorVD_resumption_one_moduleType_without_moduleId_IGN_OFF.lua
test_scripts/Resumption/InteriorVehicleData/007_InteriorVD_resumption_one_moduleType_with_moduleId_IGN_OFF.lua
test_scripts/Resumption/InteriorVehicleData/008_InteriorVD_resumption_same_moduleType_with_different_moduleIds_IGN_OFF.lua
test_scripts/Resumption/InteriorVehicleData/009_InteriorVD_resumption_all_modules_without_moduleId_IGN_OFF.lua
test_scripts/Resumption/InteriorVehicleData/010_InteriorVD_resumption_all_modules_with_moduleId_IGN_OFF.lua
test_scripts/Resumption/InteriorVehicleData/011_InteriorVD_resumption_modules_after_unsubscription_unexpected_disconnect.lua
test_scripts/Resumption/InteriorVehicleData/012_InteriorVD_resumption_modules_after_unsubscription_IGN_OFF.lua
test_scripts/Resumption/InteriorVehicleData/013_InteriorVD_resumption_two_apps_different_moduleTypes_unexpected_disconnect.lua
test_scripts/Resumption/InteriorVehicleData/014_InteriorVD_resumption_two_apps_different_moduleTypes_IGN_OFF.lua
test_scripts/Resumption/InteriorVehicleData/015_InteriorVD_resumption_two_apps_same_moduleTypes_same_moduleIds_unexpected_disconnect.lua
test_scripts/Resumption/InteriorVehicleData/016_InteriorVD_resumption_two_apps_same_moduleTypes_same_moduleIds_IGN_OFF.lua
test_scripts/Resumption/InteriorVehicleData/017_InteriorVD_resumption_two_apps_same_moduleTypes_different_moduleIds_unexpected_disconnect.lua
test_scripts/Resumption/InteriorVehicleData/018_InteriorVD_resumption_two_apps_same_moduleTypes_different_moduleIds_IGN_OFF.lua
test_scripts/Resumption/InteriorVehicleData/019_InteriorVD_resumption_two_apps_multiple_moduleTypes_unexpected_disconnect.lua
test_scripts/Resumption/InteriorVehicleData/020_InteriorVD_resumption_two_apps_multiple_moduleTypes_IGN_OFF.lua
test_scripts/Resumption/InteriorVehicleData/021_InteriorVD_resumption_in_3rd_ignition_cycle.lua
test_scripts/Resumption/InteriorVehicleData/025_InteriorVD_resumption_double_subscription_without_moduleId_unexpected_disconnect.lua
test_scripts/Resumption/InteriorVehicleData/026_InteriorVD_resumption_double_subscription_with_moduleId_unexpected_disconnect.lua
test_scripts/Resumption/InteriorVehicleData/commonResumptionsInteriorVD.lua

ATF Test Scripts
This PR is **not ready** for review.
Refactored scripts
develop
- [х] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

[SDL-0188] Refactor InteriorVD_resumption scripts

---

test_scripts/Resumption/Handling_errors_from_HMI/002_successful_resumption_other_successful_result_codes.lua
test_scripts/Resumption/Handling_errors_from_HMI/007_resume_all_data_with_one_rpc_2apps_unexpected_disconnect.lua
test_scripts/Resumption/Handling_errors_from_HMI/008_resume_all_data_with_one_rpc_2apps_ign_off.lua
test_scripts/Resumption/Handling_errors_from_HMI/013_resume_one_rpc_late_response_unexpected_disconnect.lua
test_scripts/Resumption/Handling_errors_from_HMI/014_resume_one_rpc_late_response_ign_off.lua
test_scripts/Resumption/Handling_errors_from_HMI/019_resume_all_data_without_response_to_one_rpc_2apps_unexpected_disconnect.lua
test_scripts/Resumption/Handling_errors_from_HMI/020_resume_all_data_without_response_to_one_rpc_2apps_ign_off.lua
test_scripts/Resumption/Handling_errors_from_HMI/054_resume_IVD_subscription_after_erroneous_response_all_moduleTypes.lua
test_scripts/Resumption/Handling_errors_from_HMI/055_resume_IVD_subscription_without_response_all_moduleTypes.lua
test_scripts/Resumption/Handling_errors_from_HMI/056_resume_IVD_subscription_after_erroneous_response_different_moduleTypes_2_apps.lua
test_scripts/Resumption/Handling_errors_from_HMI/057_resume_IVD_subscription_without_response_different_moduleTypes_2_apps.lua
test_scripts/Resumption/Handling_errors_from_HMI/058_resume_IVD_subscription_after_erroneous_response_same_moduleTypes_different_moduleIds_2_apps.lua
test_scripts/Resumption/Handling_errors_from_HMI/059_resume_IVD_subscription_without_response_same_moduleTypes_different_moduleIds_2_apps.lua
test_scripts/Resumption/Handling_errors_from_HMI/060_resume_IVD_subscription_after_erroneous_response_2_apps_waiting_for_IVD_response_for_app2.lua
test_scripts/Resumption/Handling_errors_from_HMI/commonResumptionErrorHandling.lua

A set of fixes related to feature

 [SDL-0188] fixup! Various updates

---

test_scripts/Resumption/Handling_errors_from_HMI/053_Another_RPC_IVD_delayed_response_from_HMI.lua
test_scripts/Resumption/Handling_errors_from_HMI/054_resume_IVD_subscription_after_erroneous_response_all_moduleTypes.lua
test_scripts/Resumption/Handling_errors_from_HMI/055_resume_IVD_subscription_without_response_all_moduleTypes.lua
test_scripts/Resumption/Handling_errors_from_HMI/056_resume_IVD_subscription_after_erroneous_response_different_moduleTypes_2_apps.lua
test_scripts/Resumption/Handling_errors_from_HMI/057_resume_IVD_subscription_without_response_different_moduleTypes_2_apps.lua
test_scripts/Resumption/Handling_errors_from_HMI/058_resume_IVD_subscription_after_erroneous_response_same_moduleTypes_different_moduleIds_2_apps.lua
test_scripts/Resumption/Handling_errors_from_HMI/059_resume_IVD_subscription_without_response_same_moduleTypes_different_moduleIds_2_apps.lua
test_scripts/Resumption/Handling_errors_from_HMI/060_resume_IVD_subscription_after_erroneous_response_2_apps_waiting_for_IVD_response_for_app2.lua

Extended log messages for GetIVD

[SDL-0188] Extended log messages for GetIVD

---

test_scripts/Defects/7_0/3164_1_OnInteriorVehicleData_empty_module_data.lua
test_scripts/Defects/7_0/3164_2_GetInteriorVehicleData_empty_module_data_to_cache.lua
test_scripts/Defects/7_0/3164_3_GetInteriorVehicleData_empty_module_data_from_cache.lua
test_sets/Defects/Defects_release_7_0.txt
user_modules/sequences/remote_control.lua

ATF Test Scripts to check #[FORDTCN-7343](https://adc.luxoft.com/jira/browse/FORDTCN-7343)
According to a detailed analysis of fix, the issue relates to saving of empty moduleData  in the cache
- New scripts for 3164 issue
- Update of test set with new created scripts
- Update of remote_control.lua module with non mandatory `pPTUpdateFunc` 
develop

Script for issue 3164

---

test_scripts/Protocol/NACKReason/005_Wrong_app_type_Video_Audio_Services_NACK.lua
test_scripts/Protocol/NACKReason/006_Wrong_HMI_level_Video_Audio_Services_NACK.lua
test_scripts/Protocol/NACKReason/007_Force_protected_Video_Audio_Services_NACK.lua
test_scripts/Protocol/NACKReason/008_Force_not_protected_Video_Audio_Services_NACK.lua
test_scripts/Protocol/NACKReason/009_PTU_failed_Video_Service_NACK.lua
test_scripts/Protocol/NACKReason/010_PTU_failed_Audio_Service_NACK.lua
test_scripts/Protocol/NACKReason/011_PTU_failed_RPC_Service_NACK.lua
test_scripts/Protocol/NACKReason/012_Invalid_time_Video_Service_NACK.lua
test_scripts/Protocol/NACKReason/013_Invalid_time_Audio_Service_NACK.lua
test_scripts/Protocol/NACKReason/014_Invalid_time_RPC_Service_NACK.lua
test_scripts/Protocol/NACKReason/015_Second_unprotected_Video_Audio_RPC_Services_NACK.lua
test_scripts/Protocol/commonProtocol.lua
test_sets/protocol_nak_reason_param.txt

ATF Test Scripts to check #[FORDTCN-7953](https://adc.luxoft.com/jira/browse/FORDTCN-7953)
Extending coverage for feature 0308 `Add a Reason Parameter to All Protocol NAKs`
develop

[SDL-0308] Extending coverage for feature

---

test_scripts/API/VehicleData/GenericNetworkSignalData/commonGenericNetSignalData.lua
test_scripts/API/VehicleData/common.lua

ATF Test Scripts to check #[FORDTCN-10826](https://adc.luxoft.com/jira/browse/FORDTCN-10826)
Update existed vehicle data scripts for `climateData`
[feature/7.1.0_version_bump](https://github.com/smartdevicelink/sdl_atf/tree/feature/7.1.0_version_bump)
- updated the existed vehicle data scripts with `climateData`
- updated the `GNSD` scripts with `climateData`
- removed redundant data type and if conditions in `GNSD` scripts

[SDL-0269] Test scripts update for "New vehicle data ClimateData" feature

---

test_scripts/API/VehicleData/GenericNetworkSignalData/commonGenericNetSignalData.lua

ATF Test Scripts to check #[FORDTCN-10827](https://adc.luxoft.com/jira/browse/FORDTCN-10827)
[Update existed vehicle data scripts for Enhance BodyInformation vehicle data]
[[feature/7.1.0_version_bump](https://github.com/smartdevicelink/sdl_atf/tree/feature/7.1.0_version_bump)]
- updated the GNSD scripts with Enhance BodyInformation vehicle data params

[SDL-0255] Test scripts update for "Enhance BodyInformation vehicle data"

---

test_scripts/Defects/7_1/3163_SDL_restart_with_gear_change.lua
test_sets/Defects/Defects_release_7_1.txt

ATF Test Scripts to check #[FORDTCN-7342](https://adc.luxoft.com/jira/browse/FORDTCN-7342)
Script for checking 3163 issue
develop
- new script with a covering of SDL restart with gear changing

[Issue-3163] Script for checking SDL restart with gear changing

---

test_scripts/Protocol/Enable_OEM_exclusive_apps_support/010.lua
test_scripts/Protocol/Enable_OEM_exclusive_apps_support/011.lua
test_scripts/Protocol/Enable_OEM_exclusive_apps_support/012_1.lua
test_scripts/Protocol/Enable_OEM_exclusive_apps_support/012_2.lua
test_scripts/Protocol/commonProtocol.lua

ATF Test Scripts to check 
https://adc.luxoft.com/jira/browse/FORDTCN-11090
https://adc.luxoft.com/jira/browse/FORDTCN-11091
https://adc.luxoft.com/jira/browse/FORDTCN-11092

[SDL-0293] Processing the systemHardwareVersion

---

test_scripts/Defects/7_1/3668_App_resets_UserLocation.lua
test_sets/Defects/Defects_release_7_1.txt

ATF Test Scripts to check 3668
develop
New scripts
New test set for the issues in scope of 7.1 release

Add scripts for issue 3668 (internal review)

---

test_scripts/Defects/7_1/1896_SDL_does_not_send_HeartBeat_request_to_Mobile_HeartBeatTimeout_is_Zero.lua
test_sets/Defects/Defects_release_7_1.txt

ATF Test Scripts to check # [FORDTCN-11656](https://adc.luxoft.com/jira/browse/FORDTCN-11656)
New ATF script to check the issue.
develop
- Added new scripts
- Updated test set for 7.1 release with new scripts

Add test script for issue 1896 (Internal review)

---

test_scripts/Defects/7_1/1585_AlertManeuver_UNSUPPORTED_RESOURCE_response_success.lua
test_sets/Defects/Defects_release_7_1.txt

ATF Test Scripts to check [FORDTCN-11698](https://adc.luxoft.com/jira/browse/FORDTCN-11698)
This PR is ready for internal review.
develop
New scripts

Add scripts for issue 1585

---

test_scripts/Defects/7_1/1619_AlertManeuer_empty_SoftButtons_missing_Info.lua
test_sets/Defects/Defects_release_7_1.txt

ATF Test Scripts to check [FORDTCN-11700](https://adc.luxoft.com/jira/browse/FORDTCN-11700)
This PR is ready for internal review.
develop
New scripts

Add test script for 1619 (Internal review)

---

test_scripts/API/VehicleData/OnVehicleData/009_OnVD_allowed_for_omitted_parameters_field.lua
test_sets/API/vehicle_data.txt

ATF Test Scripts to check [FORDTCN-12049](https://adc.luxoft.com/jira/browse/FORDTCN-12049)
develop
Added new scripts
Updated test set for the issues in scope of 7.2 release

[Issue-2380] Add script for issue 2380 [internal review]

---

test_scripts/Defects/7_0/3169_Multiple_ignition_cycles.lua
test_sets/Defects/Defects_release_7_0.txt

ATF Test Scripts to check #[issue number in sdl_core repository]
develop
Added new scripts
Updated test set for the issues in scope of 7.0 release

[Issue-3169] Add script for issue 3169 [internal review]

---

test_scripts/Defects/7_0/3170_AddCommand_DeleteCommand_multiple_times.lua
test_sets/Defects/Defects_release_7_0.txt

ATF Test Scripts to check #[issue number in sdl_core repository]
develop
Added new scripts
Updated test set for the issues in scope of 7.0 release

[Issue-3170] Add script for issue 3170 [internal review]

---

test_scripts/Defects/7_1/1600_SetGlobalProperties_UNSUPPORTED_RESOURCE_response_success.lua
test_sets/Defects/Defects_release_7_1.txt

ATF Test Scripts to check [FORDTCN-11697](https://adc.luxoft.com/jira/browse/FORDTCN-11697)
This PR is ready for internal review.
develop
New scripts

Add scripts for issue 1600 (Internal review)

---

test_scripts/Defects/5_1/1002_SDL_sends_StopAudioStream_in_case_User_Exit_during_Audio_Video_streaming.lua
test_sets/Defects/Defects_releases_4_x_and_5_x.txt

ATF Test Scripts to check [FORDTCN-11982](https://adc.luxoft.com/jira/browse/FORDTCN-11982)
develop

[Issue-1002] Add script for issue 1002 [internal review]
